DROP TABLE "QUIZ";                  -- 퀴즈
DROP TABLE "RECORD";                -- 학생시청기록
DROP TABLE "ENROLLMENT_STUDENT";    -- 수강신청_학생
DROP TABLE "ASSIGNMENT_FILE";       -- 댓글 첨부파일
DROP TABLE "REFERENCE_FILE";        -- 자료 첨부파일
DROP TABLE "WEEK_INFORMATION";      -- 주차별 정보
DROP TABLE "COMMENT";               --과제게시판 댓글
DROP TABLE "REFERENCE";             --강의자료
DROP TABLE "SUBJECT";               --과목
DROP TABLE "ACADEMIC_CALENDAR";     --학사일정_달력
DROP TABLE "MESSAGE";               --메세지
DROP TABLE "NOTICE";                --공지사항
DROP TABLE "ASSIGNMENT_LIST";       -- 과제 게시판
DROP TABLE "MEMBER";                -- 회원
DROP TABLE "DEPARTMENT";            -- 소속



--DROP TABLE WEEK_INFORMATION CASCADE CONSTRAINTS;

CREATE TABLE "NOTICE" (
	"BOARD_NOTICE_NO"	NUMBER		NOT NULL,
	"BOARD_NOTICE_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_NOTICE__WRITER"	VARCHAR2(30)		NOT NULL,
	"BOARD_NOTICE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_NOTICE_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."ID" IS '학생:S 교수: P 관리자 :M';


CREATE TABLE "ASSIGNMENT_LIST" (
	"BOARD_ASSIGNMENT_NO"	NUMBER		NOT NULL,
	"BOARD_ASSIGNMENT_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_ASSIGNMENT_WRITER"	VARCHAR2(30)		NOT NULL,
	"BOARD_ASSIGNMENT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_ASSIGNMENT_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "ASSIGNMENT_LIST"."ID" IS '학생:S 교수: P 관리자 :M';



CREATE TABLE "ASSIGNMENT_FILE" (
	"BOARD_FILE_NO"	NUMBER		NOT NULL,
	"BOARD_FILE_NAME"	VARCHAR2(300)		NOT NULL,
	"BOARD_FILE_ADD"	BFILE		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL
);



CREATE TABLE "ACADEMIC_CALENDAR" (
	"ACADEMIC_NO"	NUMBER		NOT NULL,
	"ACADEMIC_NAME"	VARCHAR2(60)		NOT NULL,
	"START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"END_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."ACADEMIC_NO" IS '시퀀스';



CREATE TABLE "SUBJECT" (
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL,
	"SUBJECT_NAME"	VARCHAR2(30)		NOT NULL,
	"COURSE_GRADE"	NUMBER(1)		NOT NULL,
	"COURSE_SEMESTER"	NUMBER(4)		NOT NULL,
	"COURSE_CREDIT"	NUMBER(1)		NOT NULL,
	"COURSE_CLASS"	VARCHAR2(90)		NOT NULL,
	"COURSE_CAPACITY"	NUMBER		NOT NULL,
	"OPEN_YN"	VARCHAR2(3)		NOT NULL,
	"DEPT_CODE"	VARCHAR2(4)		NOT NULL,
	"CLASS_TYPE"	VARCHAR2(12)		NULL,
	"COURSE_DAY"	VARCHAR2(3)		NULL,
	"COURSE_PERIOD"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "SUBJECT"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';

COMMENT ON COLUMN "SUBJECT"."COURSE_SEMESTER" IS 'ex)2201,2202,2301,2302';

COMMENT ON COLUMN "SUBJECT"."DEPT_CODE" IS '컴공:C, 실음:M, 관리자:ADMIN';

COMMENT ON COLUMN "SUBJECT"."CLASS_TYPE" IS '전공선택/전공필수';



CREATE TABLE "DEPARTMENT" (
	"DEPT_CODE"	VARCHAR2(20)		NOT NULL,
	"DEPT_NAME"	VARCHAR2(20)		NOT NULL,
	"DEPT_OPACITY"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DEPARTMENT"."DEPT_CODE" IS '컴공:C 실음:M 관리자 : ADMIN';



CREATE TABLE "REFERENCE" (
	"REF_NO"	NUMBER		NOT NULL,
	"REF_TITLE"	VARCHAR2(60)		NOT NULL,
	"REF_CONTENT"	VARCHAR2(900)		NOT NULL,
	"REF_WRITER"	VARCHAR2(30)		NOT NULL,
	"REF_WRITE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "REFERENCE"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "ENROLLMENT_STUDENT" (
	"ID"	VARCHAR2(12)		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ENROLLMENT_STUDENT"."ID" IS '학생:S , 교수:P, 관리자:M';

COMMENT ON COLUMN "ENROLLMENT_STUDENT"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "WEEK_INFORMATION" (
	"LECTURE_NO"	VARCHAR2(255)		NOT NULL,
	"WEEK"	VARCHAR2(255)		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL,
	"PERIOD"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"VIDEO_LINK"	VARCHAR2(900)		NOT NULL,
	"VIDEO_LENGTH"	NUMBER		NOT NULL,
	"VIDEO_TITLE"	VARCHAR2(40)		NOT NULL
);

COMMENT ON COLUMN "WEEK_INFORMATION"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';

COMMENT ON COLUMN "WEEK_INFORMATION"."PERIOD" IS 'systimestamp+7days';

COMMENT ON COLUMN "WEEK_INFORMATION"."VIDEO_TITLE" IS 'ex) 스마트 콘텐츠-6주차-12강';



CREATE TABLE "REFERENCE_FILE" (
	"REF_FILE_NO"	NUMBER		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL,
	"REF_FILE_NAME"	VARCHAR2(90)		NOT NULL,
	"REF_FILE_TYPE"	VARCHAR2(30)		NOT NULL,
	"REF_FILE_ADD"	BFILE		NOT NULL
);



CREATE TABLE "RECORD" (
	"LECTURE_NO"	VARCHAR2(255)		NOT NULL,
	"WEEK"	VARCHAR2(255)		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL,
	"PLAYTIME"	NUMBER	DEFAULT 0	NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "RECORD"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';

COMMENT ON COLUMN "RECORD"."ID" IS '학생:S 교수: P 관리자 :M';



CREATE TABLE "QUIZ" (
	"LECTURE_NO"	VARCHAR2(255)		NOT NULL,
	"WEEK"	VARCHAR2(255)		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL,
	"QUIZ_SCORE"	NUMBER		NOT NULL,
	"QUIZ_CNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QUIZ"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "MESSAGE" (
	"MSG_NO"	NUMBER		NOT NULL,
	"MSG_TITLE"	VARCHAR2(150)		NOT NULL,
	"MSG_CONTENT"	VARCHAR2(900)		NOT NULL,
	"MSG_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"RECEVIER"	VARCHAR2(30)		NOT NULL,
	"SENDER"	VARCHAR2(30)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

ALTER TABLE MESSAGE DROP COLUMN ID;


CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(12)		NOT NULL,
	"NAME"	VARCHAR2(30)		NOT NULL,
	"PWD"	VARCHAR2(30)		NOT NULL,
	"RNUM"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(300)		NOT NULL,
	"ADDRESS"	VARCHAR2(600)		NOT NULL,
	"DEPT_CODE"	VARCHAR2(20)		NOT NULL
);

--비밀번호 100자리로 변경(암호화)
ALTER TABLE MEMBER MODIFY (PWD VARCHAR2(100));


COMMENT ON COLUMN "MEMBER"."ID" IS '학생:S 교수: P 관리자 :M';

COMMENT ON COLUMN "MEMBER"."DEPT_CODE" IS '컴공:C 실음:M 관리자 : ADMIN';



CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_WRITER"	VARCHAR2(30)		NOT NULL,
	"COMMENT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(500)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL,
	"BOARD_ASSIGNMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."ID" IS '학생:S 교수: P 관리자 :M';

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"BOARD_NOTICE_NO"
);

ALTER TABLE "ASSIGNMENT_LIST" ADD CONSTRAINT "PK_ASSIGNMENT_LIST" PRIMARY KEY (
	"BOARD_ASSIGNMENT_NO"
);

ALTER TABLE "ASSIGNMENT_FILE" ADD CONSTRAINT "PK_ASSIGNMENT_FILE" PRIMARY KEY (
	"BOARD_FILE_NO"
);

ALTER TABLE "ACADEMIC_CALENDAR" ADD CONSTRAINT "PK_ACADEMIC_CALENDAR" PRIMARY KEY (
	"ACADEMIC_NO"
);

ALTER TABLE "SUBJECT" ADD CONSTRAINT "PK_SUBJECT" PRIMARY KEY (
	"SUBJECT_CODE"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPT_CODE"
);

ALTER TABLE "REFERENCE" ADD CONSTRAINT "PK_REFERENCE" PRIMARY KEY (
	"REF_NO"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "PK_ENROLLMENT_STUDENT" PRIMARY KEY (
	"ID",
	"SUBJECT_CODE"
);

ALTER TABLE "WEEK_INFORMATION" ADD CONSTRAINT "PK_WEEK_INFORMATION" PRIMARY KEY (
	"LECTURE_NO",
	"WEEK",
	"SUBJECT_CODE"
);

ALTER TABLE "REFERENCE_FILE" ADD CONSTRAINT "PK_REFERENCE_FILE" PRIMARY KEY (
	"REF_FILE_NO",
	"REF_NO"
);

ALTER TABLE "RECORD" ADD CONSTRAINT "PK_RECORD" PRIMARY KEY (
	"LECTURE_NO",
	"WEEK",
	"SUBJECT_CODE"
);

ALTER TABLE "QUIZ" ADD CONSTRAINT "PK_QUIZ" PRIMARY KEY (
	"LECTURE_NO",
	"WEEK",
	"SUBJECT_CODE"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MSG_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ASSIGNMENT_LIST" ADD CONSTRAINT "FK_MEMBER_TO_ASG_LIST" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ASSIGNMENT_FILE" ADD CONSTRAINT "FK_COMMENT_TO_ASG_FILE" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "SUBJECT" ADD CONSTRAINT "FK_DEPT_TO_SUBJECT" FOREIGN KEY (
	"DEPT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPT_CODE"
);

ALTER TABLE "REFERENCE" ADD CONSTRAINT "FK_SUBJECT_TO_REF_1" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "FK_MEMBER_TO_ENROLL_ST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "FK_SUBJECT_TO_ENROLL_ST" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "WEEK_INFORMATION" ADD CONSTRAINT "FK_SUBJECT_TO_WEEK_INFO" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "REFERENCE_FILE" ADD CONSTRAINT "FK_REF_TO_REF_FILE" FOREIGN KEY (
	"REF_NO"
)
REFERENCES "REFERENCE" (
	"REF_NO"
);



ALTER TABLE "RECORD" ADD CONSTRAINT "FK_WEEK_INFO_TO_REC" FOREIGN KEY (
	"LECTURE_NO",
    "WEEK",
    "SUBJECT_CODE"
    
)
REFERENCES "WEEK_INFORMATION" (
	"LECTURE_NO",
	"WEEK",
	"SUBJECT_CODE"
);
ALTER TABLE "RECORD" ADD CONSTRAINT "FK_WEEK_INFO_TO_REC_2" FOREIGN KEY("ID") REFERENCES "MEMBER" ("ID");


ALTER TABLE "QUIZ" ADD CONSTRAINT "FK_WEEK_INFO_TO_QUIZ_1" FOREIGN KEY (
	"LECTURE_NO",
    "WEEK",
    "SUBJECT_CODE"
)
REFERENCES "WEEK_INFORMATION" (
	"LECTURE_NO",
    "WEEK",
    "SUBJECT_CODE"
);





ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MSG_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_DEPT_TO_MEMBER_1" FOREIGN KEY (
	"DEPT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPT_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_ASG_LIST_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_ASSIGNMENT_NO"
)
REFERENCES "ASSIGNMENT_LIST" (
	"BOARD_ASSIGNMENT_NO"
);



-- 테스트 insert

--INSERT DEPARTMENT
INSERT INTO DEPARTMENT VALUES ('M001','실용음악과',40);
INSERT INTO DEPARTMENT VALUES ('C001','컴퓨터공학과',40);
INSERT INTO DEPARTMENT VALUES ('ADMIN','관리자',5);

-- INSERT MEMBER
INSERT INTO MEMBER VALUES ('S1111','아무개', '1111','950722-1012345','aaaa@aaa.com','천안시 서북구 서부대로 648-13', 'M001');
INSERT INTO MEMBER VALUES ('P1111','박교수', '0','730216-1011111','bbb@bbb.com','천안시 서북구 성정로 75','M001');





-- INSERT SUBJECT
INSERT INTO SUBJECT VALUES ('TEMP','임시',1,2201,3,'폼생관203호','40','Y','M001','전공선택','월','1교시');
INSERT INTO SUBJECT VALUES ('TEMP2','임시2',1,2201,3,'폼생관204호','30','Y','M001','전공선택','월','1교시');

-- INSERT ENROLLMENT_STUDENT
INSERT INTO ENROLLMENT_STUDENT VALUES('S1111','TEMP');
INSERT INTO ENROLLMENT_STUDENT VALUES('S1111','TEMP2');


--INSERT MESSAGE
DESC MESSAGE;
INSERT INTO MESSAGE VALUES (1,'임시용 메세지','임시용 메세지 입니다.',SYSTIMESTAMP,'P1111','S1111');



-- ??학생이 신청한 과목을 보여주는 쿼리
SELECT NAME, SUBJECT_NAME
FROM
(SELECT NAME,SUBJECT_CODE
FROM ENROLLMENT_STUDENT JOIN MEMBER USING(ID)) ES JOIN SUBJECT S
ON ES.SUBJECT_CODE = S.SUBJECT_CODE
WHERE NAME = '아무개';




SELECT NAME,SUBJECT_CODE
FROM ENROLLMENT_STUDENT JOIN MEMBER USING(ID);

SELECT * FROM DEPARTMENT;
SELECT * FROM MEMBER;

SELECT * 
FROM MEMBER JOIN DEPARTMENT USING(DEPT_CODE);


COMMIT;












