--INSERT TABLE "DEPARTMENT";
--INSERT TABLE "MEMBER";
--INSERT TABLE "ASSIGNMENT_LIST";
--INSERT TABLE "NOTICE";
--INSERT TABLE "MESSAGE";
--INSERT TABLE "ACADEMIC_CALENDAR";
--INSERT TABLE "SUBJECT";
--INSERT TABLE "REFERENCE";
--INSERT TABLE "COMMENT";
--INSERT TABLE "WEEK_LECTURE";
--INSERT TABLE "REFERENCE_FILE";
--INSERT TABLE "ASSIGNMENT_FILE";
--INSERT TABLE "ENROLLMENT_STUDENT";
--INSERT TABLE "RECORD";


DROP TABLE "RECORD";
DROP TABLE "ENROLLMENT_STUDENT";
DROP TABLE "ASSIGNMENT_FILE";
DROP TABLE "REFERENCE_FILE";
DROP TABLE "WEEK_LECTURE";
DROP TABLE "COMMENT";
DROP TABLE "REFERENCE";
DROP TABLE "SUBJECT";
DROP TABLE "ACADEMIC_CALENDAR";
DROP TABLE "MESSAGE";
DROP TABLE "NOTICE";
DROP TABLE "ASSIGNMENT_LIST";
DROP TABLE "MEMBER";
DROP TABLE "DEPARTMENT";


--DROP SEQUENCE
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_ASG_NO;
DROP SEQUENCE SEQ_ASG_FILE_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_ACADEMIC_NO;
DROP SEQUENCE SEQ_MSG_NO;
DROP SEQUENCE SEQ_REC_NO;
DROP SEQUENCE SEQ_REFERENCE_NO;
DROP SEQUENCE SEQ_REF_FILE_NO;



CREATE TABLE "NOTICE" (
	"BOARD_NOTICE_NO"	NUMBER		NOT NULL,
	"BOARD_NOTICE_TITLE"	VARCHAR2(150)		NOT NULL,
    "BOARD_NOTICE_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"BOARD_NOTICE_WRITER"	VARCHAR2(30)		NOT NULL,
	"BOARD_NOTICE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."BOARD_NOTICE_NO" IS 'SEQ_NOTICE_NO';
COMMENT ON COLUMN "NOTICE"."ID" IS '학생:S 교수: P 관리자 :M';



CREATE TABLE "ASSIGNMENT_LIST" (
	"BOARD_ASSIGNMENT_NO"	NUMBER		NOT NULL,
	"BOARD_ASSIGNMENT_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_ASSIGNMENT_WRITER"	VARCHAR2(30)		NOT NULL,
	"BOARD_ASSIGNMENT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_ASSIGNMENT_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "ASSIGNMENT_LIST"."BOARD_ASSIGNMENT_NO" IS 'SEQ_ASG_NO';
COMMENT ON COLUMN "ASSIGNMENT_LIST"."ID" IS '학생:S 교수: P 관리자 :M';



CREATE TABLE "ASSIGNMENT_FILE" (
	"BOARD_FILE_NO"	NUMBER		NOT NULL,
	"BOARD_FILE_NAME"	VARCHAR2(300)		NOT NULL,
	"BOARD_FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ASSIGNMENT_FILE"."BOARD_FILE_NO" IS 'SEQ_ASG_FILE_NO';



CREATE TABLE "ACADEMIC_CALENDAR" (
	"ACADEMIC_NO"	NUMBER		NOT NULL,
	"ACADEMIC_NAME"	VARCHAR2(60)		NOT NULL,
	"START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"END_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."ACADEMIC_NO" IS 'SEQ_ACADEMIC_NO';



CREATE TABLE "SUBJECT" (
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL,
	"SUBJECT_NAME"	VARCHAR2(30)		NOT NULL,
	"COURSE_GRADE"	NUMBER(1)		NOT NULL,
	"COURSE_SEMESTER"	NUMBER(4)		NOT NULL,
	"COURSE_CREDIT"	NUMBER(1)		NOT NULL,
	"COURSE_CLASS"	VARCHAR2(90)		NOT NULL,
	"COURSE_CAPACITY"	NUMBER		NOT NULL,
	"OPEN_YN"	VARCHAR2(3)		NOT NULL,
	"DEPT_CODE"	VARCHAR2(4)		NOT NULL,
	"CLASS_TYPE"	VARCHAR2(12)		NULL,
	"COURSE_DAY"	VARCHAR2(3)		NULL,
	"COURSE_PERIOD"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "SUBJECT"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';
COMMENT ON COLUMN "SUBJECT"."COURSE_SEMESTER" IS 'ex)2201,2202,2301,2302';
COMMENT ON COLUMN "SUBJECT"."DEPT_CODE" IS '컴공:C, 실음:M, 관리자:ADMIN';
COMMENT ON COLUMN "SUBJECT"."CLASS_TYPE" IS '전공선택/전공필수';



CREATE TABLE "DEPARTMENT" (
	"DEPT_CODE"	VARCHAR2(20)		NOT NULL,
	"DEPT_NAME"	VARCHAR2(20)		NOT NULL,
	"DEPT_OPACITY"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "DEPARTMENT"."DEPT_CODE" IS '컴공:C 실음:M 관리자 : ADMIN';



CREATE TABLE "REFERENCE" (
	"REF_NO"	NUMBER		NOT NULL,
	"REF_TITLE"	VARCHAR2(60)		NOT NULL,
	"REF_CONTENT"	VARCHAR2(900)		NOT NULL,
	"REF_WRITER"	VARCHAR2(30)		NOT NULL,
	"REF_WRITE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "REFERENCE"."REF_NO" IS 'SEQ_REF_NO';
COMMENT ON COLUMN "REFERENCE"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "ENROLLMENT_STUDENT" (
	"ID"	VARCHAR2(12)		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ENROLLMENT_STUDENT"."ID" IS '학생:S , 교수:P, 관리자:M';
COMMENT ON COLUMN "ENROLLMENT_STUDENT"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "REFERENCE_FILE" (
	"REF_FILE_NO"	NUMBER		NOT NULL,
	"REF_FILE_NAME"	VARCHAR2(90)		NOT NULL,
	"REF_FILE_PATH"	VARCHAR2(1000)		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL
);



CREATE TABLE "MESSAGE" (
	"MSG_NO"	NUMBER		NOT NULL,
	"MSG_TITLE"	VARCHAR2(150)		NOT NULL,
	"MSG_CONTENT"	VARCHAR2(900)		NOT NULL,
	"MSG_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"RECEVIER"	VARCHAR2(30)		NOT NULL,
	"SENDER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MSG_NO" IS 'SEQ_MSG_NO';



CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(12)		NOT NULL,
	"NAME"	VARCHAR2(30)		NOT NULL,
	"PWD"	VARCHAR2(100)		NOT NULL,
	"RNUM"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(300)		NOT NULL,
	"ADDRESS"	VARCHAR2(600)		NOT NULL,
	"DEPT_CODE"	VARCHAR2(20)		NOT NULL,
	"PNUM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."ID" IS '학생:S 교수: P 관리자 :M';
COMMENT ON COLUMN "MEMBER"."DEPT_CODE" IS '컴공:C 실음:M 관리자 : ADMIN';



CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_WRITER"	VARCHAR2(30)		NOT NULL,
	"COMMENT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(500)		NOT NULL,
	"ID"	VARCHAR2(12)		NOT NULL,
	"BOARD_ASSIGNMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS 'SEQ_COMMENT_NO';
COMMENT ON COLUMN "COMMENT"."ID" IS '학생:S 교수: P 관리자 :M';



CREATE TABLE "WEEK_LECTURE" (
	"LECTURE_NO"	NUMBER		NOT NULL,
	"WEEK_NO"	NUMBER		NOT NULL,
	"VIDEO_TITLE"	VARCHAR2(100)		NOT NULL,
	"VIDEO_LINK"	VARCHAR2(900)		NOT NULL,
	"VIDEO_LENGTH"	NUMBER		NOT NULL,
	"UPLOAD_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"PERIOD"	TIMESTAMP		NOT NULL,
	"SUBJECT_CODE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "WEEK_LECTURE"."LECTURE_NO" IS 'NVL(MAX(L_NO),0) +1';
COMMENT ON COLUMN "WEEK_LECTURE"."WEEK_NO" IS 'EX) 2201';
COMMENT ON COLUMN "WEEK_LECTURE"."VIDEO_LENGTH" IS '영상길이는 초로 변환';
COMMENT ON COLUMN "WEEK_LECTURE"."UPLOAD_DATE" IS 'D';
COMMENT ON COLUMN "WEEK_LECTURE"."PERIOD" IS '업로드날짜 + 7일';
COMMENT ON COLUMN "WEEK_LECTURE"."SUBJECT_CODE" IS 'ex) C001,C002,M001,M002';



CREATE TABLE "RECORD" (
	"REC_NO"	NUMBER		NOT NULL,
	"PLAYTIME"	NUMBER	DEFAULT 0	NOT NULL,
	"LECTURE_NO"	NUMBER		NOT NULL,
	"MID"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "RECORD"."REC_NO" IS '시퀀스';
COMMENT ON COLUMN "RECORD"."LECTURE_NO" IS 'NVL(MAX(L_NO),0) +1';



ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"BOARD_NOTICE_NO"
);

ALTER TABLE "ASSIGNMENT_LIST" ADD CONSTRAINT "PK_ASG_LIST" PRIMARY KEY (
	"BOARD_ASSIGNMENT_NO"
);

ALTER TABLE "ASSIGNMENT_FILE" ADD CONSTRAINT "PK_ASG_FILE" PRIMARY KEY (
	"BOARD_FILE_NO"
);

ALTER TABLE "ACADEMIC_CALENDAR" ADD CONSTRAINT "PK_ACADEMIC_CALENDAR" PRIMARY KEY (
	"ACADEMIC_NO"
);

ALTER TABLE "SUBJECT" ADD CONSTRAINT "PK_SUBJECT" PRIMARY KEY (
	"SUBJECT_CODE"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPT_CODE"
);

ALTER TABLE "REFERENCE" ADD CONSTRAINT "PK_REFERENCE" PRIMARY KEY (
	"REF_NO"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "PK_ENROLL_ST" PRIMARY KEY (
	"ID",
	"SUBJECT_CODE"
);

ALTER TABLE "REFERENCE_FILE" ADD CONSTRAINT "PK_REF_FILE" PRIMARY KEY (
	"REF_FILE_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MSG_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "WEEK_LECTURE" ADD CONSTRAINT "PK_WEEK_LECTURE" PRIMARY KEY (
	"LECTURE_NO"
);

ALTER TABLE "RECORD" ADD CONSTRAINT "PK_RECORD" PRIMARY KEY (
	"REC_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ASSIGNMENT_LIST" ADD CONSTRAINT "FK_MEMBER_TO_ASG_LIST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ASSIGNMENT_FILE" ADD CONSTRAINT "FK_COMMENT_TO_ASG_FILE_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "SUBJECT" ADD CONSTRAINT "FK_DEPT_TO_SUBJECT_1" FOREIGN KEY (
	"DEPT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPT_CODE"
);

ALTER TABLE "REFERENCE" ADD CONSTRAINT "FK_SUBJECT_TO_REF_1" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "FK_MEMBER_TO_ENROLL_ST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "ENROLLMENT_STUDENT" ADD CONSTRAINT "FK_SUBJECT_TO_ENROLL_ST_1" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "REFERENCE_FILE" ADD CONSTRAINT "FK_REF_TO_REF_FILE_1" FOREIGN KEY (
	"REF_NO"
)
REFERENCES "REFERENCE" (
	"REF_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_DEPT_TO_MEMBER_1" FOREIGN KEY (
	"DEPT_CODE"
)
REFERENCES "DEPARTMENT" (
	"DEPT_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_ASG_LIST_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_ASSIGNMENT_NO"
)
REFERENCES "ASSIGNMENT_LIST" (
	"BOARD_ASSIGNMENT_NO"
);

ALTER TABLE "WEEK_LECTURE" ADD CONSTRAINT "FK_SUBJECT_TO_WEEK_LECTURE_1" FOREIGN KEY (
	"SUBJECT_CODE"
)
REFERENCES "SUBJECT" (
	"SUBJECT_CODE"
);

ALTER TABLE "RECORD" ADD CONSTRAINT "FK_WEEK_LECTURE_TO_RECORD_1" FOREIGN KEY (
	"LECTURE_NO"
)
REFERENCES "WEEK_LECTURE" (
	"LECTURE_NO"
);
--CREATE SEQUENCE
--NOTICE
CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--ASG_LIST
CREATE SEQUENCE SEQ_ASG_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--COMMENT
CREATE SEQUENCE SEQ_COMMENT_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--ASG_FILE
CREATE SEQUENCE SEQ_ASG_FILE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--ASG_FILE
CREATE SEQUENCE SEQ_ACADEMIC_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--MESSAGE
CREATE SEQUENCE SEQ_MSG_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--RECORD
CREATE SEQUENCE SEQ_REC_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--REFERENCE
CREATE SEQUENCE SEQ_REFERENCE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;
--REFERENCE_FILE
CREATE SEQUENCE SEQ_REF_FILE_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE
;


--TEST INSERT
--수강기간 계산법(timestamp)
--SELECT SYSTIMESTAMP + (INTERVAL '7' DAY) FROM DUAL; --수강기간 컬럼 입력용
--SELECT (TO_CHAR(ROUND(SYSTIMESTAMP + (INTERVAL '7' DAY)),'YY/MM/DD HH24:MI:SS')) FROM DUAL; - 사용자 화면 출력용



INSERT INTO DEPARTMENT VALUES ('C001','컴퓨터공학과',40);
INSERT INTO MEMBER VALUES ('S1111','아무개','0','960722-1111111','AAA@NAVER.COM','천안시 서북구','C001','010-1111-2222');
INSERT INTO SUBJECT VALUES('C0101','JAVA기초','1','2201','3','폼생관 202호','40','Y','C001','전공필수','월','1교시');

-- 공지사항 값 입력시 INSERT 쿼리문
INSERT INTO NOTICE VALUES ((SEQ_NOTICE_NO.NEXTVAL), '테스트 공지사항 제목' ,'테스트 공지사항내용',(SELECT NAME FROM MEMBER WHERE NAME='아무개'), 
                    SYSTIMESTAMP, (SELECT ID FROM MEMBER WHERE ID = 'S1111'));

ALTER TABLE SUBJECT MODIFY (OPEN_YN DEFAULT 'Y');
ALTER TABLE SUBJECT MODIFY (DEPT_CODE VARCHAR2(20));

ALTER TABLE SUBJECT ADD (PF_ID VARCHAR2(12));
ALTER TABLE SUBJECT ADD CONSTRAINT FK_PF_ID FOREIGN KEY(PF_ID) REFERENCES MEMBER (ID);

ALTER TABLE REFERENCE DROP CONSTRAINT FK_SUBJECT_TO_REF_1;

ALTER TABLE REFERENCE ADD CONSTRAINT "FK_SUBJECT_TO_REF_1" FOREIGN KEY (SUBJECT_CODE)
REFERENCES SUBJECT (SUBJECT_CODE) ON DELETE CASCADE;

--강의번호, 주차, 과목코드 빼고 나머지 null로 변경
--수강기간 컬럼 삭제
--파일이름 컬럼 생성

ALTER TABLE WEEK_LECTURE MODIFY VIDEO_TITLE NULL;
ALTER TABLE WEEK_LECTURE MODIFY VIDEO_LINK NULL;
ALTER TABLE WEEK_LECTURE MODIFY VIDEO_LENGTH NULL;
ALTER TABLE WEEK_LECTURE MODIFY UPLOAD_DATE NULL;
ALTER TABLE WEEK_LECTURE DROP COLUMN PERIOD;
ALTER TABLE WEEK_LECTURE ADD FILE_NAME VARCHAR2(100);
ALTER TABLE WEEK_LECTURE ADD FILE_PATH VARCHAR2(200) DEFAULT '' NOT NULL;
ALTER TABLE WEEK_LECTURE DROP COLUMN VIDEO_LINK;

COMMIT;
